services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: notesphere-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_strong_password123!"
    ports:
      - "1433:1433"
    volumes:
      - notesphere_sql_data:/var/opt/mssql
    restart: always

volumes:
  notesphere_sql_data:
